---
data_model: ensemble
fit_model: ensemble
t: 8
theta: 1
sigma.f: 0.5
sigma.s: 0
p.s: 0.5
y0: 0
B: 10  # number of batches
R: 100 # number of reps per batch
d: 1000
L: 
  - 1
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
save_draws?: no
save_all_time_steps?: no
save_pre_adj_draws?: no
save_all_pre_adj_time_steps?: no
...
